import {
    ColorSchemeScript,
    MantineProvider,
    Notification,
} from "@mantine/core";
import type { Metadata } from "next";
import "@mantine/core/styles.css";
import "mantine-datatable/styles.layer.css";
import "./layout.css";

export const metadata: Metadata = {
    title:       "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <ColorSchemeScript />
        </head>
        <body>
            <MantineProvider>
                <Notification />
                { children }
            </MantineProvider>
        </body>
        </html>
    );
}
